version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: iQbe
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - db
    volumes:
      - /node_modules
      - .:iQbe
  db:
    image: mariadb:11
    container_name: iqbe-db
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./iqbe-data:/var/lib/mysql/data
    networks:
      - iqbe-network

volumes:
  iqbe-data:
    driver: local

networks:
  iqbe-network:
    driver: bridge