version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    network_mode: service:db
    volumes:
      - ../:/iQbe:cached
    
  db:
    image: mysql:9.1
    container_name: iqbe-db
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - dev.env
    command:
      - --sql-mode=NO_ENGINE_SUBSTITUTION
    
volumes:
  mysql-data:
