name: release-please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHubs App token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - uses: google-github-actions/release-please-action@v3
        with: 
          token: ${{ steps.generate_token.outputs.token }}
          release-type: node
          package-name: release-please-iqbe